<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);BenchmarkSuite1/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CosineKitty.AstronomyEngine" Version="2.1.19" />
    <PackageReference Include="LibVLCSharp" Version="3.9.1" />
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TelescopeWatcher\" />
    <Compile Remove="BenchmarkSuite1\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
    <None Include=".github\skills\telescopeconfiguration\SKILL.md" />
    <None Include=".github\skills\reasearch_telescope_skill\SKILL.md" />
  </ItemGroup>

</Project>
